web.http.port=8181
web.http.path=/api
web.http.identity.port=8182
web.http.identity.path=/api/identity
web.http.credentials.port=10001
web.http.credentials.path=/api/credentials
web.http.presentation.port=10001
web.http.presentation.path=/api/credentials

edc.vault.hashicorp.url=http://edc_identity_hub_vault:8200
edc.vault.hashicorp.token=root
edc.vault.hashicorp.secrets.path=secret/data/

edc.iam.sts.privatekey.alias=shared-private-key
edc.iam.sts.publickey.id=shared-key
edc.mvd.credentials.path=/app/identity-hub/shared/credentials
